name: ExecuteShell

on:
  #schedule:
  #  - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        # cat .env

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    #- name: Generate key
    #  run: php artisan key:generate  --env=duwbai
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: git clone
      run: |
        git clone https://${{ secrets.REPO_TOKEN }}@github.com/lilahliza/planetscale.git planetscale
        # cp -r planetscale/sh  ./
        cp -r planetscale/env  ./
        ls -la ./sh
        cat ./sh/exec_env.sh
        ls -la ./env
    - name: Create Dir
      run: |
        # mkdir -p ./app/Console/Commands/Test
        # touch ./app/Console/Commands/Test/TestEnvServer.php
        # mkdir -p ./sh
        # touch ./sh/exec_env.sh
        # mkdir -p ./env
        # touch ./env/.b43d45.env
        php artisan command:test_env_server  --env=duwbai
        ls -la ./env
    - name: Execute Shell
      run: |
        cat ./sh/exec_env.sh
        # bash ./sh/exec_env.sh
        # php artisan command:test_env_server  --env=b43d45
        # php artisan command:test_env_server  --env=4b3d45

    - name: update file
      run: |
        date_y=`date "+%Y-%m-%d %H:%M:%S"`
        month_y=`date "+%m"`
        day_y=`date "+%d"`
        if [ "${day_y}" == "12" ]; then
          echo "${date_y}" > monthly.log
        else
          echo "${date_y}" >> monthly.log
        fi
    - name: git log
      run: |
        git log
    - name: git status
      run: |
        git status
    - name: git diff
      run: |
        git diff ./
    - name: push
      run: |
        git config --local user.name github-actions[bot]
        git config --local user.email github-actions[bot]@users.noreply.github.com
        git add ./
        git commit -m "update"
        git push origin
