name: ExecuteShell

on:
  workflow_dispatch:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Dir
      run: |
        # mkdir -p ./app/Console/Commands/Test
        # touch ./app/Console/Commands/Test/TestEnvServer.php
        # mkdir -p ./sh
        # touch ./sh/exec_env.sh
        # mkdir -p ./env
        # touch ./env/.4b3d45.env
        php artisan command:test_env_server  --env=4b3d45
    - name: Execute Shell
      run: bash ./sh/exec_env.sh
    - name: push
      run: |
        git config --local user.name github-actions[bot]
        git config --local user.email github-actions[bot]@users.noreply.github.com
        git status
        git add ./
        git commit -m "update"
        git log
        git push origin
