name: Laravel

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: install laravel provec
      run: |
        echo ""
        composer create-project  laravel/laravel blog "10.6.1"
        # composer create-project --prefer-dist laravel/laravel blog "10.*"
        # laravel/laravel：包名，表示创建一个laravel项目
        # blog：项目目录
        # --prefer-dist：使用压缩版
        # 10.*：laravel版本
        # 文档 https://learnku.com/docs/laravel/10.x/releasesmd/14832

    - name: ls
      run: |
        # ls -la ./
        echo ""
    - name: ls_blog
      run: |
        # echo ""
        ls -la /etc/ssl/certs/ca-certificates.crt
        # ls -la ./blog
        mv ./blog/*  ./
        # ls -la ./blog
        # ls -la ./
        mv ./blog/.editorconfig  ./.editorconfig
        mv ./blog/.env  ./.env
        mv ./blog/.env.example  ./.env.example
        mv ./blog/.gitattributes  ./.gitattributes
        mv ./blog/.gitignore  ./.gitignore
        # -rw-r--r--  1 runner docker  258 Mar  8 16:57 .editorconfig
        # -rw-r--r--  1 runner docker 1120 Apr  5 13:42 .env
        # -rw-r--r--  1 runner docker 1069 Mar  8 16:57 .env.example
        # -rw-r--r--  1 runner docker  186 Mar  8 16:57 .gitattributes
        # -rw-r--r--  1 runner docker  243 Mar  8 16:57 .gitignore
        ls -la ./blog
        ls -la ./
        # cat .gitignore
    # - name: Copy .env
    #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    # - name: Generate key
    #   run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    # - name: Create Database
    #   run: |
    #     mkdir -p database
    #     touch database/database.sqlite
    # - name: Execute tests (Unit and Feature tests) via PHPUnit
    #   env:
    #     DB_CONNECTION: sqlite
    #     DB_DATABASE: database/database.sqlite
    #     MYSQL_ATTR_SSL_CA: /etc/ssl/certs/ca-certificates.crt
    #   run: vendor/bin/phpunit
    # - name: version
    #   run: |
    #     php artisan --version
    #     php --version
    # - name: view file
    #   run: |
    #     cat .env
    - name: update file
      run: |
        date_y=`date "+%Y-%m-%d %H:%M:%S"`
        month_y=`date "+%m"`
        if [ "${month_y}" == "12" ]; then
          echo "${date_y}" > monthly.log
        else
          echo "${date_y}" >> monthly.log
        fi
    - name: push
      run: |
        git config --local user.name github-actions[bot]
        git config --local user.email github-actions[bot]@users.noreply.github.com
        git status
        # git add monthly.log
        git add ./
        # git commit -m "Monthly update"
        git commit -m "init laravel 10.6.1"
        git log
        git push origin
